# Main plugin settings

# Default plugin language.
# Built-in languages:
# - en
# - ru
language: en

# Permission node for staff members
admin-permission: ticketsystem.admin

# Time in seconds before a staff member gets a reminder about an active ticket
reminder-interval: 60

# Time in seconds before an accepted ticket is released automatically
auto-release-time: 300
