name: TicketSystem
version: 1.0.0
main: me.kawasaki.tickets.TicketSystemPlugin
api-version: 1.16
author: Kawasaki
description: Ticket system for players to contact administrators
softdepend: [StaffWork]

commands:
  ac:
    description: Обратиться к администратору
    usage: /ac [ТЕКСТ]
  tickets:
    description: Панель управления тикетами
    usage: /tickets
    permission: ticketsystem.admin

